name: Security Testing

on: [push, pull_request]

jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Scan for vulnerabilities in dependencies
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      # Run OWASP ZAP baseline scan (this doesn't require the app to be running)
      - name: OWASP ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.9.0
        with:
          target: "https://www.example.com" # This is just a placeholder, ZAP will still check your code

      # SonarCloud Analysis (static code analysis)
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Create Security Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: security-report
          path: |
            ./*zap*
            ./snyk-report
