name: Security Testing

on: [push, pull_request]

jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install Dependencies
        run: |
          cd ex-arbete
          npm install

      - name: Build Next.js
        run: |
          cd ex-arbete
          npm run build

      - name: Start Next.js (Background)
        run: |
          cd ex-arbete
          npm run start &
          sleep 10 # Give the server time to start

      # Now run security tests
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      - name: OWASP ZAP Full Scan
        uses: zaproxy/action-full-scan@v0.7.0
        with:
          target: "http://localhost:3000"

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      # Generate Security Report
      - name: Create Security Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: security-report
          path: |
            ./*zap*
            ./snyk-report

      # Optional: Fail if critical vulnerabilities found
      - name: Check for Critical Issues
        if: always()
        run: |
          if grep -q "Critical" ./security-report/*; then
            echo "Critical security issues found!"
            exit 1
          fi
