name: Security Testing

on: [push, pull_request]

jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Run Snyk to check for vulnerabilities
        id: snyk
        uses: snyk/actions/node@master
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      - name: Check Snyk Results
        if: always()
        run: |
          if [[ "${{ steps.snyk.outcome }}" == "failure" ]]; then
            echo "::warning::⚠️ SNYK SECURITY VULNERABILITIES FOUND ⚠️"
          fi

      - name: OWASP ZAP Baseline Scan
        id: zap_scan
        uses: zaproxy/action-baseline@v0.9.0
        with:
          target: "https://www.example.com"
          allow_issue_writing: false
        continue-on-error: true

      - name: Check ZAP Scan Results
        if: always()
        run: |
          if [[ "${{ steps.zap_scan.outputs.alerts }}" == *"WARN-NEW:"* ]]; then
            echo "::warning::⚠️ OWASP ZAP SECURITY WARNINGS FOUND ⚠️"
            echo "::warning::----------------------------------------"
            echo "${{ steps.zap_scan.outputs.alerts }}" | grep "WARN-NEW:" | while read -r line; do
              echo "::warning::$line"
            done
            echo "::warning::----------------------------------------"
            echo "::warning::Total Warnings: $(echo "${{ steps.zap_scan.outputs.alerts }}" | grep -c "WARN-NEW:")"
          fi

      - name: SonarCloud Scan
        uses: SonarSource/sonarqube-scan-action@v5.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.projectKey=AdamOhlson1_Ex-arbete-test2
            -Dsonar.organization=adamohlson1

      - name: Upload Reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: security-reports
          path: |
            ./*.txt
            ./*.html
            ./*.json
